import test from 'node:test';
import assert from 'node:assert/strict';
import { PDFDocument, PDFName, PDFString, PDFRawStream } from 'pdf-lib';
import * as pako from 'pako';
import { preparePdfForPdfx4 } from '../src/services/pdfxPreparation.ts';
import {
  finalizePdfx4Document,
  verifyPdfx4FinalizedDocument,
  type PdfxFinalizeResult,
} from '../src/services/pdfxFinalize.ts';
import { extractPdfStructure } from '../server/pdfExtractor.ts';
import { runDeterministicRuleEngine } from '../src/utils/ruleEngine.ts';
import { evaluatePdfx4Eligibility } from '../src/services/pdfxEligibility.ts';
import { COMMERCIAL_PRINT_300DPI_PROFILE } from '../src/utils/productionProfiles.ts';

/**
 * Creates a synthetic PDF ready for full preparation -> finalization pipeline:
 * - 90x50 mm trim target (MediaBox 96x56 mm = 3mm bleed margin)
 * - 1 RGB raster image 10x10 px (FlateDecode)
 * - Missing OutputIntent
 * - Missing TrimBox/BleedBox
 */
async function createFixableTestPdf(): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const pageW = (96 * 72) / 25.4;
  const pageH = (56 * 72) / 25.4;
  const page = doc.addPage([pageW, pageH]);

  const rawRgb = new Uint8Array(10 * 10 * 3);
  for (let i = 0; i < rawRgb.length; i += 3) {
    rawRgb[i] = 255;
    rawRgb[i + 1] = 100;
    rawRgb[i + 2] = 50;
  }
  const flateBytes = pako.deflate(rawRgb);

  const imgDict = doc.context.obj({
    Type: 'XObject',
    Subtype: 'Image',
    Width: 10,
    Height: 10,
    BitsPerComponent: 8,
    ColorSpace: 'DeviceRGB',
    Filter: 'FlateDecode',
  });
  const imgStream = PDFRawStream.of(imgDict as any, flateBytes);
  const imgRef = doc.context.register(imgStream);

  page.node.set(
    PDFName.of('Resources'),
    doc.context.obj({ XObject: { Im1: imgRef } })
  );

  return await doc.save({ useObjectStreams: false });
}

test('1. End-to-End: Original -> Preparation -> Finalize -> Reopen -> Motor 1 -> verifiedPdfX = true', async () => {
  const originalBytes = await createFixableTestPdf();

  // Phase 2: Preparation
  const prepResult = await preparePdfForPdfx4(originalBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
    allowFallbackSrgb: true,
    destinationIccPresetId: 'cgats_tr_001_swop',
  });

  assert.equal(prepResult.success, true);
  assert.equal(prepResult.status, 'prepared');
  assert.equal(prepResult.eligibleAfterPreparation.eligible, true);
  // Verified is STILL false in Phase 2
  assert.equal(prepResult.verifiedPdfX, false);
  assert.ok(prepResult.pdfBytes);

  // Phase 3: Finalization & Verification
  const finalizeResult: PdfxFinalizeResult = await finalizePdfx4Document(prepResult.pdfBytes!, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
    destinationIccPresetId: 'cgats_tr_001_swop',
    title: 'ArteCheck Teste PDF/X-4',
  });

  assert.equal(finalizeResult.success, true, 'Finalização deve ter sucesso');
  assert.equal(finalizeResult.declaredPdfX, 'PDF/X-4', 'declaredPdfX deve ser PDF/X-4');
  assert.equal(finalizeResult.verifiedPdfX, true, 'verifiedPdfX DEVE ser true após validação do arquivo serializado');
  assert.equal(finalizeResult.targetStandard, 'PDF/X-4');
  assert.ok(finalizeResult.finalizedPdfBytes, 'Buffer finalizado deve existir');
  assert.notEqual(finalizeResult.preparedSha256, finalizeResult.finalizedSha256);

  // Verify all checks passed
  assert.equal(finalizeResult.checks.length, 9);
  assert.ok(finalizeResult.checks.every((c) => c.status === 'passed'));

  // Independent re-extraction of the generated bytes to confirm PDF/X-4 markers
  const reExtracted = await extractPdfStructure(finalizeResult.finalizedPdfBytes!);
  assert.equal(reExtracted.pdfxInfo?.isDeclaredPdfX, true);
  assert.ok(reExtracted.pdfxInfo?.declaredVersion?.includes('PDF/X-4'));
  assert.equal(reExtracted.pdfxInfo?.hasXmpMetadata, true);
  assert.ok(reExtracted.pdfxInfo?.xmpPdfxVersion?.includes('PDF/X-4'));
  assert.equal(reExtracted.colorSummary.hasRgb, false);
  assert.equal(reExtracted.colorSummary.hasCmyk, true);
});

test('2. Negativo: Documento não elegível (pre-condição false) -> recusa finalização', async () => {
  // Fresh non-prepared document with RGB and missing OutputIntent
  const unPreparedPdf = await createFixableTestPdf();

  const finalizeResult = await finalizePdfx4Document(unPreparedPdf, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });

  assert.equal(finalizeResult.success, false, 'Deve recusar finalização');
  assert.equal(finalizeResult.verifiedPdfX, false, 'verifiedPdfX deve ser false');
  assert.equal(finalizeResult.declaredPdfX, null, 'Não deve declarar PDF/X');
  assert.ok(finalizeResult.failures.length > 0);
});

test('3. Negativo: Metadata PDF/X escrita mas Output Intent ausente -> verifiedPdfX = false', async () => {
  // Create a clean PDF with PDF/X metadata injected manually, but NO Output Intent
  const doc = await PDFDocument.create();
  doc.addPage([200, 200]);
  const infoDict = doc.context.obj({
    GTS_PDFXVersion: PDFString.of('PDF/X-4'),
    GTS_PDFXConformance: PDFString.of('PDF/X-4'),
  });
  doc.context.trailerInfo.Info = doc.context.register(infoDict);
  const pdfBytes = await doc.save({ useObjectStreams: false });

  const structure = await extractPdfStructure(pdfBytes);
  const rules = runDeterministicRuleEngine(structure, COMMERCIAL_PRINT_300DPI_PROFILE);
  const eligibility = evaluatePdfx4Eligibility(structure, { profile: COMMERCIAL_PRINT_300DPI_PROFILE, ruleResults: rules });

  const verification = verifyPdfx4FinalizedDocument(structure, rules, eligibility);
  assert.equal(verification.verified, false, 'verifiedPdfX deve ser false sem OutputIntent');
  assert.ok(verification.failures.some((f) => f.includes('VERIFY_OUTPUT_INTENT')));
});

test('4. Negativo: Metadata escrita mas fonte não incorporada -> verifiedPdfX = false', async () => {
  const structure: any = {
    pageCount: 1,
    pages: [{ page: 1, widthMm: 90, heightMm: 50, mediaBox: { xPt: 0, yPt: 0, widthPt: 255, heightPt: 141 }, trimBox: { status: 'explicit', xPt: 0, yPt: 0, widthPt: 255, heightPt: 141, widthMm: 90, heightMm: 50 }, bleedBox: { status: 'explicit', xPt: 0, yPt: 0, widthPt: 255, heightPt: 141 } }],
    fonts: [{ name: 'Arial', isEmbedded: false, isUsedInContent: true, format: 'TrueType' }],
    colorSummary: { hasRgb: false, hasCmyk: true, hasSpotColors: false, familiesDetected: [] },
    outputIntents: [{ subtype: 'GTS_PDFX', outputConditionIdentifier: 'CGATS TR 001', hasDestOutputProfile: true, destOutputProfile: { isValidIcc: true, colorSpace: 'CMYK', byteLength: 500000 } }],
    pdfxInfo: { isDeclaredPdfX: true, declaredVersion: 'PDF/X-4', hasXmpMetadata: true, xmpPdfxVersion: 'PDF/X-4' },
  };
  const rules = runDeterministicRuleEngine(structure, COMMERCIAL_PRINT_300DPI_PROFILE);
  const eligibility = evaluatePdfx4Eligibility(structure, { profile: COMMERCIAL_PRINT_300DPI_PROFILE, ruleResults: rules });

  const verification = verifyPdfx4FinalizedDocument(structure, rules, eligibility);
  assert.equal(verification.verified, false, 'verifiedPdfX deve ser false com fonte não incorporada');
  assert.ok(verification.failures.some((f) => f.includes('VERIFY_FONTS')));
});

test('5. Negativo: Metadata escrita mas hierarquia de caixas inválida -> verifiedPdfX = false', async () => {
  const structure: any = {
    pageCount: 1,
    pages: [{
      page: 1,
      widthMm: 90,
      heightMm: 50,
      mediaBox: { xPt: 0, yPt: 0, widthPt: 200, heightPt: 100 },
      trimBox: { status: 'explicit', xPt: 0, yPt: 0, widthPt: 300, heightPt: 200, widthMm: 105, heightMm: 70 }, // Exceeds MediaBox!
      bleedBox: { status: 'explicit', xPt: 0, yPt: 0, widthPt: 300, heightPt: 200 },
    }],
    fonts: [],
    colorSummary: { hasRgb: false, hasCmyk: true, hasSpotColors: false, familiesDetected: [] },
    outputIntents: [{ subtype: 'GTS_PDFX', outputConditionIdentifier: 'CGATS TR 001', hasDestOutputProfile: true, destOutputProfile: { isValidIcc: true, colorSpace: 'CMYK', byteLength: 500000 } }],
    pdfxInfo: { isDeclaredPdfX: true, declaredVersion: 'PDF/X-4', hasXmpMetadata: true, xmpPdfxVersion: 'PDF/X-4' },
  };
  const rules = runDeterministicRuleEngine(structure, COMMERCIAL_PRINT_300DPI_PROFILE);
  const eligibility = evaluatePdfx4Eligibility(structure, { profile: COMMERCIAL_PRINT_300DPI_PROFILE, ruleResults: rules });

  const verification = verifyPdfx4FinalizedDocument(structure, rules, eligibility);
  assert.equal(verification.verified, false, 'verifiedPdfX deve ser false com caixas inconsistentes');
});

test('6. Negativo: Documento criptografado com declaração PDF/X -> verifiedPdfX = false', async () => {
  const structure: any = {
    pageCount: 1,
    isEncrypted: true,
    pages: [],
    fonts: [],
    colorSummary: { hasRgb: false, hasCmyk: true, hasSpotColors: false, familiesDetected: [] },
    outputIntents: [{ subtype: 'GTS_PDFX', outputConditionIdentifier: 'CGATS TR 001', hasDestOutputProfile: true, destOutputProfile: { isValidIcc: true, colorSpace: 'CMYK', byteLength: 500000 } }],
    pdfxInfo: { isDeclaredPdfX: true, declaredVersion: 'PDF/X-4', hasXmpMetadata: true, xmpPdfxVersion: 'PDF/X-4' },
  };
  const rules = runDeterministicRuleEngine(structure, COMMERCIAL_PRINT_300DPI_PROFILE);
  const eligibility = evaluatePdfx4Eligibility(structure, { profile: COMMERCIAL_PRINT_300DPI_PROFILE, ruleResults: rules });

  const verification = verifyPdfx4FinalizedDocument(structure, rules, eligibility);
  assert.equal(verification.verified, false, 'verifiedPdfX deve ser false com criptografia');
  assert.ok(verification.failures.some((f) => f.includes('VERIFY_SECURITY')));
});

test('7. Regressão: Documento com perfil comercial genérico (sem expectedWidthMm) -> caixas inferidas dinamicamente -> verifiedPdfX = true', async () => {
  const originalBytes = await createFixableTestPdf();

  // Preparation using generic commercial profile
  const prep = await preparePdfForPdfx4(originalBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
    allowFallbackSrgb: true,
  });

  assert.equal(prep.success, true);
  assert.ok(prep.pdfBytes);

  // Re-extracted prepared document must have explicit TrimBox and BleedBox
  const prepStruct = await extractPdfStructure(prep.pdfBytes);
  assert.equal(prepStruct.pages[0].trimBox?.status, 'explicit');
  assert.equal(prepStruct.pages[0].bleedBox?.status, 'explicit');

  // Finalize & verify
  const fin = await finalizePdfx4Document(prep.pdfBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });

  assert.equal(fin.success, true);
  assert.equal(fin.declaredPdfX, 'PDF/X-4');
  assert.equal(fin.verifiedPdfX, true, 'verifiedPdfX deve ser true com caixas dinâmicas inferidas');
  assert.equal(fin.failures.length, 0);
});

test('8. End-to-End Real: MediaBox 96x56 mm + bleed 3mm -> TrimBox 90x50 mm, BleedBox 96x56 mm, declaredVersion "PDF/X-4" -> verifiedPdfX = true', async () => {
  // Create original PDF with MediaBox 96x56 mm (272.126 x 158.740 pt)
  const doc = await PDFDocument.create();
  const widthPt = (96 * 72) / 25.4;
  const heightPt = (56 * 72) / 25.4;
  const page = doc.addPage([widthPt, heightPt]);

  const rawRgb = new Uint8Array(10 * 10 * 3);
  for (let i = 0; i < rawRgb.length; i += 3) {
    rawRgb[i] = 200;
    rawRgb[i + 1] = 80;
    rawRgb[i + 2] = 40;
  }
  const flateBytes = pako.deflate(rawRgb);
  const imgDict = doc.context.obj({
    Type: 'XObject',
    Subtype: 'Image',
    Width: 10,
    Height: 10,
    BitsPerComponent: 8,
    ColorSpace: 'DeviceRGB',
    Filter: 'FlateDecode',
  });
  const imgStream = PDFRawStream.of(imgDict as any, flateBytes);
  const imgRef = doc.context.register(imgStream);
  page.node.set(PDFName.of('Resources'), doc.context.obj({ XObject: { Im1: imgRef } }));
  const originalBytes = await doc.save({ useObjectStreams: false });

  // Phase 2: Prepare
  const prep = await preparePdfForPdfx4(originalBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
    allowFallbackSrgb: true,
  });

  assert.equal(prep.success, true);
  assert.equal(prep.status, 'prepared');
  assert.ok(prep.pdfBytes);

  // Validate step statuses
  const boxesStep = prep.steps.find((s) => s.code === 'PDFX_PREP_BOXES');
  assert.equal(boxesStep?.status, 'applied');

  // Re-extract prepared structure
  const prepStruct = await extractPdfStructure(prep.pdfBytes);
  const prepPage = prepStruct.pages[0];
  assert.equal(prepPage.mediaBox.widthMm, 96);
  assert.equal(prepPage.mediaBox.heightMm, 56);
  assert.equal(prepPage.trimBox?.status, 'explicit');
  assert.equal(prepPage.trimBox?.widthMm, 90);
  assert.equal(prepPage.trimBox?.heightMm, 50);
  assert.equal(prepPage.bleedBox?.status, 'explicit');
  assert.equal(prepPage.bleedBox?.widthMm, 96);
  assert.equal(prepPage.bleedBox?.heightMm, 56);

  // Phase 3: Finalize
  const fin = await finalizePdfx4Document(prep.pdfBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });

  assert.equal(fin.success, true);
  assert.equal(fin.declaredPdfX, 'PDF/X-4');
  assert.equal(fin.verifiedPdfX, true);
  assert.equal(fin.failures.length, 0);

  // Re-extract finalized structure and assert PDF/X-4 declaredVersion has the slash
  const finStruct = await extractPdfStructure(fin.finalizedPdfBytes!);
  assert.equal(finStruct.pdfxInfo?.declaredVersion, 'PDF/X-4', 'declaredVersion DEVE conter a barra normativa PDF/X-4');
  assert.equal(finStruct.pdfxInfo?.xmpPdfxVersion, 'PDF/X-4');
  assert.equal(finStruct.pdfxInfo?.isDeclaredPdfX, true);

  // Verify all checks passed in finalizer
  for (const c of fin.checks) {
    assert.equal(c.status, 'passed', `Check ${c.code} deve ser passed`);
  }
});

test('7. QA 08: Transparência viva preservada, estrutura xref íntegra e sem necessidade de reparo', async () => {
  // Create original PDF with ReportLab-like structure:
  // - A4 page (216x303 mm MediaBox for 210x297 mm Trim + 3mm Bleed)
  // - ExtGState with ca = 0.45
  // - Content stream with /gRLs0 gs
  // - Declared but unrendered Helvetica font
  const doc = await PDFDocument.create();
  const pageW = (216 * 72) / 25.4;
  const pageH = (303 * 72) / 25.4;
  const page = doc.addPage([pageW, pageH]);

  const extGStateDict = doc.context.obj({
    Type: 'ExtGState',
    ca: 0.45,
  });
  const extGStateRef = doc.context.register(extGStateDict);

  const fontDict = doc.context.obj({
    Type: 'Font',
    Subtype: 'Type1',
    BaseFont: 'Helvetica',
    Encoding: 'WinAnsiEncoding',
  });
  const fontRef = doc.context.register(fontDict);

  page.node.set(
    PDFName.of('Resources'),
    doc.context.obj({
      ExtGState: { gRLs0: extGStateRef },
      Font: { F1: fontRef },
    })
  );

  // Content stream with live transparency and vector graphics (no text showing operators)
  const contentBytes = Buffer.from('1 0 0 1 0 0 cm /gRLs0 gs 0.5 g 50 50 200 200 re f', 'utf-8');
  page.node.set(
    PDFName.of('Contents'),
    doc.context.register(PDFRawStream.of(doc.context.obj({}), contentBytes))
  );

  const originalBytes = await doc.save({ useObjectStreams: false });

  // Phase 2: Prepare
  const prep = await preparePdfForPdfx4(originalBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });

  assert.equal(prep.success, true);
  assert.equal(prep.status, 'prepared');
  assert.ok(prep.pdfBytes);

  // Phase 3: Finalize
  const fin = await finalizePdfx4Document(prep.pdfBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });

  assert.equal(fin.success, true);
  assert.equal(fin.declaredPdfX, 'PDF/X-4');
  assert.equal(fin.verifiedPdfX, true);
  assert.equal(fin.failures.length, 0);

  // Assert VERIFY_SERIALIZED_STRUCTURE is passed
  const structCheck = fin.checks.find((c) => c.code === 'VERIFY_SERIALIZED_STRUCTURE');
  assert.equal(structCheck?.status, 'passed');

  // Re-extract finalized structure and assert live transparency is preserved
  const finStruct = await extractPdfStructure(fin.finalizedPdfBytes!);
  assert.equal(finStruct.pages[0].hasTransparency, true, 'Transparência viva DEVE ser preservada');

  // Inspect raw finalized PDF to ensure /ExtGState and /ca 0.45 are physically intact
  const rawFinal = Buffer.from(fin.finalizedPdfBytes!).toString('latin1');
  assert.ok(rawFinal.includes('/ExtGState'), 'ExtGState deve estar presente no PDF serializado');
  assert.ok(rawFinal.includes('0.45'), 'ca 0.45 deve estar presente no PDF serializado');
  assert.ok(rawFinal.includes('/gRLs0 gs'), 'operador /gRLs0 gs deve estar preservado no content stream');

  // Verify all checks in finalizer
  for (const c of fin.checks) {
    assert.equal(c.status, 'passed', `Check ${c.code} deve ser passed`);
  }
});

test('8. QA 09: Documento com páginas heterogêneas (A4 e 90x50) é bloqueado na preparação e na finalização direta', async () => {
  const doc = await PDFDocument.create();
  // Page 1: A4
  doc.addPage([(210 * 72) / 25.4, (297 * 72) / 25.4]);
  // Page 2: 90x50 mm
  doc.addPage([(90 * 72) / 25.4, (50 * 72) / 25.4]);

  const pdfBytes = await doc.save({ useObjectStreams: false });

  // 1. Preparation must be blocked with manual_required
  const prep = await preparePdfForPdfx4(pdfBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });

  assert.equal(prep.success, false);
  assert.equal(prep.status, 'manual_required');
  assert.equal(prep.verifiedPdfX, false);
  const geomStep = prep.eligibleAfterPreparation.checks.find((c) => c.id === 'PDFX_PAGE_SIZE_UNIFORMITY');
  assert.equal(geomStep?.status, 'manual_required');
  assert.equal(geomStep?.reasonCode, 'PDFX_HETEROGENEOUS_PAGE_SIZES');

  // 2. Direct finalization must also be blocked
  const fin = await finalizePdfx4Document(pdfBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });

  assert.equal(fin.success, false);
  assert.equal(fin.verifiedPdfX, false);
  assert.ok(fin.failures.some((f) => f.includes('PDFX_HETEROGENEOUS_PAGE_SIZES')));
});

test('9. QA 13: Documento com RGB vetorial (rg/RG) bloqueia preparação e finalização direta', async () => {
  const doc = await PDFDocument.create();
  const page = doc.addPage([(210 * 72) / 25.4, (297 * 72) / 25.4]);
  // Vector RGB content stream
  const content = Buffer.from('.9 .15 .15 rg 50 50 200 200 re f', 'utf-8');
  page.node.set(PDFName.of('Contents'), doc.context.register(PDFRawStream.of(doc.context.obj({}) as any, content)));

  const pdfBytes = await doc.save({ useObjectStreams: false });

  // 1. Preparation must be blocked with manual_required
  const prep = await preparePdfForPdfx4(pdfBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });

  assert.equal(prep.success, false);
  assert.equal(prep.verifiedPdfX, false);
  const colorCheck = prep.eligibleAfterPreparation.checks.find((c) => c.id === 'PDFX_COLOR_SPACES');
  assert.equal(colorCheck?.status, 'manual_required');
  assert.equal(colorCheck?.reasonCode, 'PDFX_RGB_VECTOR_MANUAL_REQUIRED');

  // 2. Direct finalization must fail
  const fin = await finalizePdfx4Document(pdfBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });

  assert.equal(fin.success, false);
  assert.equal(fin.verifiedPdfX, false);
  assert.ok(fin.failures.some((f) => f.includes('PDFX_RGB_VECTOR_MANUAL_REQUIRED') || f.includes('RGB')));
});

test('10. QA 19: Form XObject aninhado em 2 níveis (Page -> Fm2 -> Fm1 -> Im0) é convertido na preparação e finaliza com verifiedPdfX=true', async () => {
  const doc = await PDFDocument.create();
  const page = doc.addPage([(210 * 72) / 25.4, (297 * 72) / 25.4]);

  const rawRgb = new Uint8Array(600 * 400 * 3);
  for (let i = 0; i < rawRgb.length; i += 3) {
    rawRgb[i] = 200; rawRgb[i + 1] = 50; rawRgb[i + 2] = 50;
  }
  const deflated = pako.deflate(rawRgb);

  const imgDict = doc.context.obj({
    Type: 'XObject',
    Subtype: 'Image',
    Width: 600,
    Height: 400,
    BitsPerComponent: 8,
    ColorSpace: 'DeviceRGB',
    Filter: 'FlateDecode',
  });
  const imgStream = PDFRawStream.of(imgDict as any, deflated);
  const imgRef = doc.context.register(imgStream);

  const form1Dict = doc.context.obj({
    Type: 'XObject',
    Subtype: 'Form',
    BBox: [0, 0, 144, 96],
    Resources: { XObject: { Im0: imgRef } },
  });
  const form1Stream = PDFRawStream.of(form1Dict as any, Buffer.from('q 144 0 0 96 0 0 cm /Im0 Do Q', 'utf-8'));
  const form1Ref = doc.context.register(form1Stream);

  const form2Dict = doc.context.obj({
    Type: 'XObject',
    Subtype: 'Form',
    BBox: [0, 0, 144, 96],
    Resources: { XObject: { Fm1: form1Ref } },
  });
  const form2Stream = PDFRawStream.of(form2Dict as any, Buffer.from('q 1 0 0 1 0 0 cm /Fm1 Do Q', 'utf-8'));
  const form2Ref = doc.context.register(form2Stream);

  page.node.set(PDFName.of('Resources'), doc.context.obj({ XObject: { Fm2: form2Ref } }));
  page.node.set(PDFName.of('Contents'), doc.context.register(PDFRawStream.of(doc.context.obj({}) as any, Buffer.from('q 1 0 0 1 50 50 cm /Fm2 Do Q', 'utf-8'))));

  const origPdfBytes = await doc.save({ useObjectStreams: false });

  // 1. Direct finalization without conversion must fail with RGB_OBJECTS_PRESENT
  const forcedFin = await finalizePdfx4Document(origPdfBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });
  assert.equal(forcedFin.success, false);
  assert.equal(forcedFin.verifiedPdfX, false);

  // 2. Preparation must succeed and convert depth 2 nested image
  const prep = await preparePdfForPdfx4(origPdfBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });
  assert.equal(prep.success, true);
  assert.equal(prep.verifiedPdfX, false);

  // 3. Finalization of prepared bytes must succeed with verifiedPdfX=true
  const fin = await finalizePdfx4Document(prep.preparedPdfBytes!, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });
  assert.equal(fin.success, true);
  assert.equal(fin.verifiedPdfX, true);

  // 4. Inspect final serialized bytes
  const reExtracted = await extractPdfStructure(fin.finalizedPdfBytes!);
  assert.equal(reExtracted.pages[0].imageOccurrences.length, 1);
  assert.equal(reExtracted.pages[0].imageOccurrences[0].colorSpace, 'DeviceCMYK');
  assert.equal(reExtracted.colorSummary.hasRgb, false);
  assert.equal(reExtracted.colorSummary.hasRgbRaster, false);
});



