import test from 'node:test';
import assert from 'node:assert/strict';
import { PDFDocument, PDFName, PDFString, PDFRawStream } from 'pdf-lib';
import * as pako from 'pako';
import { preparePdfForPdfx4 } from '../src/services/pdfxPreparation.ts';
import {
  finalizePdfx4Document,
  verifyPdfx4FinalizedDocument,
  type PdfxFinalizeResult,
} from '../src/services/pdfxFinalize.ts';
import { extractPdfStructure } from '../server/pdfExtractor.ts';
import { runDeterministicRuleEngine } from '../src/utils/ruleEngine.ts';
import { evaluatePdfx4Eligibility } from '../src/services/pdfxEligibility.ts';
import { COMMERCIAL_PRINT_300DPI_PROFILE } from '../src/utils/productionProfiles.ts';

/**
 * Creates a synthetic PDF ready for full preparation -> finalization pipeline:
 * - 90x50 mm trim target (MediaBox 96x56 mm = 3mm bleed margin)
 * - 1 RGB raster image 10x10 px (FlateDecode)
 * - Missing OutputIntent
 * - Missing TrimBox/BleedBox
 */
async function createFixableTestPdf(): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const pageW = (96 * 72) / 25.4;
  const pageH = (56 * 72) / 25.4;
  const page = doc.addPage([pageW, pageH]);

  const rawRgb = new Uint8Array(10 * 10 * 3);
  for (let i = 0; i < rawRgb.length; i += 3) {
    rawRgb[i] = 255;
    rawRgb[i + 1] = 100;
    rawRgb[i + 2] = 50;
  }
  const flateBytes = pako.deflate(rawRgb);

  const imgDict = doc.context.obj({
    Type: 'XObject',
    Subtype: 'Image',
    Width: 10,
    Height: 10,
    BitsPerComponent: 8,
    ColorSpace: 'DeviceRGB',
    Filter: 'FlateDecode',
  });
  const imgStream = PDFRawStream.of(imgDict as any, flateBytes);
  const imgRef = doc.context.register(imgStream);

  page.node.set(
    PDFName.of('Resources'),
    doc.context.obj({ XObject: { Im1: imgRef } })
  );

  return await doc.save({ useObjectStreams: false });
}

test('1. End-to-End: Original -> Preparation -> Finalize -> Reopen -> Motor 1 -> verifiedPdfX = true', async () => {
  const originalBytes = await createFixableTestPdf();

  // Phase 2: Preparation
  const prepResult = await preparePdfForPdfx4(originalBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
    allowFallbackSrgb: true,
    destinationIccPresetId: 'cgats_tr_001_swop',
  });

  assert.equal(prepResult.success, true);
  assert.equal(prepResult.status, 'prepared');
  assert.equal(prepResult.eligibleAfterPreparation.eligible, true);
  // Verified is STILL false in Phase 2
  assert.equal(prepResult.verifiedPdfX, false);
  assert.ok(prepResult.pdfBytes);

  // Phase 3: Finalization & Verification
  const finalizeResult: PdfxFinalizeResult = await finalizePdfx4Document(prepResult.pdfBytes!, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
    destinationIccPresetId: 'cgats_tr_001_swop',
    title: 'ArteCheck Teste PDF/X-4',
  });

  assert.equal(finalizeResult.success, true, 'Finalização deve ter sucesso');
  assert.equal(finalizeResult.declaredPdfX, 'PDF/X-4', 'declaredPdfX deve ser PDF/X-4');
  assert.equal(finalizeResult.verifiedPdfX, true, 'verifiedPdfX DEVE ser true após validação do arquivo serializado');
  assert.equal(finalizeResult.targetStandard, 'PDF/X-4');
  assert.ok(finalizeResult.finalizedPdfBytes, 'Buffer finalizado deve existir');
  assert.notEqual(finalizeResult.preparedSha256, finalizeResult.finalizedSha256);

  // Verify all 8 checks passed
  assert.equal(finalizeResult.checks.length, 8);
  assert.ok(finalizeResult.checks.every((c) => c.status === 'passed'));

  // Independent re-extraction of the generated bytes to confirm PDF/X-4 markers
  const reExtracted = await extractPdfStructure(finalizeResult.finalizedPdfBytes!);
  assert.equal(reExtracted.pdfxInfo?.isDeclaredPdfX, true);
  assert.ok(reExtracted.pdfxInfo?.declaredVersion?.includes('PDF/X-4'));
  assert.equal(reExtracted.pdfxInfo?.hasXmpMetadata, true);
  assert.ok(reExtracted.pdfxInfo?.xmpPdfxVersion?.includes('PDF/X-4'));
  assert.equal(reExtracted.colorSummary.hasRgb, false);
  assert.equal(reExtracted.colorSummary.hasCmyk, true);
});

test('2. Negativo: Documento não elegível (pre-condição false) -> recusa finalização', async () => {
  // Fresh non-prepared document with RGB and missing OutputIntent
  const unPreparedPdf = await createFixableTestPdf();

  const finalizeResult = await finalizePdfx4Document(unPreparedPdf, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });

  assert.equal(finalizeResult.success, false, 'Deve recusar finalização');
  assert.equal(finalizeResult.verifiedPdfX, false, 'verifiedPdfX deve ser false');
  assert.equal(finalizeResult.declaredPdfX, null, 'Não deve declarar PDF/X');
  assert.ok(finalizeResult.failures.length > 0);
});

test('3. Negativo: Metadata PDF/X escrita mas Output Intent ausente -> verifiedPdfX = false', async () => {
  // Create a clean PDF with PDF/X metadata injected manually, but NO Output Intent
  const doc = await PDFDocument.create();
  doc.addPage([200, 200]);
  const infoDict = doc.context.obj({
    GTS_PDFXVersion: PDFString.of('PDF/X-4'),
    GTS_PDFXConformance: PDFString.of('PDF/X-4'),
  });
  doc.context.trailerInfo.Info = doc.context.register(infoDict);
  const pdfBytes = await doc.save({ useObjectStreams: false });

  const structure = await extractPdfStructure(pdfBytes);
  const rules = runDeterministicRuleEngine(structure, COMMERCIAL_PRINT_300DPI_PROFILE);
  const eligibility = evaluatePdfx4Eligibility(structure, { profile: COMMERCIAL_PRINT_300DPI_PROFILE, ruleResults: rules });

  const verification = verifyPdfx4FinalizedDocument(structure, rules, eligibility);
  assert.equal(verification.verified, false, 'verifiedPdfX deve ser false sem OutputIntent');
  assert.ok(verification.failures.some((f) => f.includes('VERIFY_OUTPUT_INTENT')));
});

test('4. Negativo: Metadata escrita mas fonte não incorporada -> verifiedPdfX = false', async () => {
  const structure: any = {
    pageCount: 1,
    pages: [{ page: 1, widthMm: 90, heightMm: 50, mediaBox: { xPt: 0, yPt: 0, widthPt: 255, heightPt: 141 }, trimBox: { status: 'explicit', xPt: 0, yPt: 0, widthPt: 255, heightPt: 141, widthMm: 90, heightMm: 50 }, bleedBox: { status: 'explicit', xPt: 0, yPt: 0, widthPt: 255, heightPt: 141 } }],
    fonts: [{ name: 'Arial', isEmbedded: false, isUsedInContent: true, format: 'TrueType' }],
    colorSummary: { hasRgb: false, hasCmyk: true, hasSpotColors: false, familiesDetected: [] },
    outputIntents: [{ subtype: 'GTS_PDFX', outputConditionIdentifier: 'CGATS TR 001', hasDestOutputProfile: true, destOutputProfile: { isValidIcc: true, colorSpace: 'CMYK', byteLength: 500000 } }],
    pdfxInfo: { isDeclaredPdfX: true, declaredVersion: 'PDF/X-4', hasXmpMetadata: true, xmpPdfxVersion: 'PDF/X-4' },
  };
  const rules = runDeterministicRuleEngine(structure, COMMERCIAL_PRINT_300DPI_PROFILE);
  const eligibility = evaluatePdfx4Eligibility(structure, { profile: COMMERCIAL_PRINT_300DPI_PROFILE, ruleResults: rules });

  const verification = verifyPdfx4FinalizedDocument(structure, rules, eligibility);
  assert.equal(verification.verified, false, 'verifiedPdfX deve ser false com fonte não incorporada');
  assert.ok(verification.failures.some((f) => f.includes('VERIFY_FONTS')));
});

test('5. Negativo: Metadata escrita mas hierarquia de caixas inválida -> verifiedPdfX = false', async () => {
  const structure: any = {
    pageCount: 1,
    pages: [{
      page: 1,
      widthMm: 90,
      heightMm: 50,
      mediaBox: { xPt: 0, yPt: 0, widthPt: 200, heightPt: 100 },
      trimBox: { status: 'explicit', xPt: 0, yPt: 0, widthPt: 300, heightPt: 200, widthMm: 105, heightMm: 70 }, // Exceeds MediaBox!
      bleedBox: { status: 'explicit', xPt: 0, yPt: 0, widthPt: 300, heightPt: 200 },
    }],
    fonts: [],
    colorSummary: { hasRgb: false, hasCmyk: true, hasSpotColors: false, familiesDetected: [] },
    outputIntents: [{ subtype: 'GTS_PDFX', outputConditionIdentifier: 'CGATS TR 001', hasDestOutputProfile: true, destOutputProfile: { isValidIcc: true, colorSpace: 'CMYK', byteLength: 500000 } }],
    pdfxInfo: { isDeclaredPdfX: true, declaredVersion: 'PDF/X-4', hasXmpMetadata: true, xmpPdfxVersion: 'PDF/X-4' },
  };
  const rules = runDeterministicRuleEngine(structure, COMMERCIAL_PRINT_300DPI_PROFILE);
  const eligibility = evaluatePdfx4Eligibility(structure, { profile: COMMERCIAL_PRINT_300DPI_PROFILE, ruleResults: rules });

  const verification = verifyPdfx4FinalizedDocument(structure, rules, eligibility);
  assert.equal(verification.verified, false, 'verifiedPdfX deve ser false com caixas inconsistentes');
});

test('6. Negativo: Documento criptografado com declaração PDF/X -> verifiedPdfX = false', async () => {
  const structure: any = {
    pageCount: 1,
    isEncrypted: true,
    pages: [],
    fonts: [],
    colorSummary: { hasRgb: false, hasCmyk: true, hasSpotColors: false, familiesDetected: [] },
    outputIntents: [{ subtype: 'GTS_PDFX', outputConditionIdentifier: 'CGATS TR 001', hasDestOutputProfile: true, destOutputProfile: { isValidIcc: true, colorSpace: 'CMYK', byteLength: 500000 } }],
    pdfxInfo: { isDeclaredPdfX: true, declaredVersion: 'PDF/X-4', hasXmpMetadata: true, xmpPdfxVersion: 'PDF/X-4' },
  };
  const rules = runDeterministicRuleEngine(structure, COMMERCIAL_PRINT_300DPI_PROFILE);
  const eligibility = evaluatePdfx4Eligibility(structure, { profile: COMMERCIAL_PRINT_300DPI_PROFILE, ruleResults: rules });

  const verification = verifyPdfx4FinalizedDocument(structure, rules, eligibility);
  assert.equal(verification.verified, false, 'verifiedPdfX deve ser false com criptografia');
  assert.ok(verification.failures.some((f) => f.includes('VERIFY_SECURITY')));
});

test('7. Regressão: Documento com perfil comercial genérico (sem expectedWidthMm) -> caixas inferidas dinamicamente -> verifiedPdfX = true', async () => {
  const originalBytes = await createFixableTestPdf();

  // Preparation using generic commercial profile
  const prep = await preparePdfForPdfx4(originalBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
    allowFallbackSrgb: true,
  });

  assert.equal(prep.success, true);
  assert.ok(prep.pdfBytes);

  // Re-extracted prepared document must have explicit TrimBox and BleedBox
  const prepStruct = await extractPdfStructure(prep.pdfBytes);
  assert.equal(prepStruct.pages[0].trimBox?.status, 'explicit');
  assert.equal(prepStruct.pages[0].bleedBox?.status, 'explicit');

  // Finalize & verify
  const fin = await finalizePdfx4Document(prep.pdfBytes, {
    profile: COMMERCIAL_PRINT_300DPI_PROFILE,
  });

  assert.equal(fin.success, true);
  assert.equal(fin.declaredPdfX, 'PDF/X-4');
  assert.equal(fin.verifiedPdfX, true, 'verifiedPdfX deve ser true com caixas dinâmicas inferidas');
  assert.equal(fin.failures.length, 0);
});
